services:
  emqx:
    image: emqx/emqx:latest
    hostname: emqx
    restart: always
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"  # HTTP API
      - "8883:8883"  # MQTT TLS
      - "18083:18083" # WS
    environment:
      - EMQX_NAME=emqx
    #  - EMQX_HOST=emqx.imm.local
    #  - EMQX_NODE__NAME=emqx@emqx.imm.local
    #  - EMQX_LISTENERS__TCP__EXTERNAL__BIND=0.0.0.0:1883  # MQTT
    #  - EMQX_LISTENERS__WS__EXTERNAL__BIND=0.0.0.0:8083   # Dashboard
      - EMQX_DASHBOARD__DEFAULT_LOGIN__USER=admin
      - EMQX_DASHBOARD__DEFAULT_LOGIN__PASS=public
    volumes:
      - emqx_data:/opt/emqx/data
      - emqx_log:/opt/emqx/log
    #  - ./emqx.conf:/opt/emqx/etc/emqx.conf  # my config
    networks:
      - imm-net
    healthcheck:
      test: ["CMD", "emqx_ctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: imm_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: public
    ports: ["5432:5432"]
    volumes:
    - pg-data:/var/lib/postgresql/data
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks: [imm-net]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  emulator:
    build: ./ImmMqttEmulator
    depends_on: 
      emqx:
        condition: service_healthy    
    networks: [imm-net]

  subscriber:
    build: ./MqttToPg
    depends_on: 
      emqx:
        condition: service_healthy    
      postgres:
        condition: service_healthy    

    restart: unless-stopped
    networks: [imm-net]

volumes:
  emqx_data:
  emqx_log:
  pg-data: {}

networks:
  imm-net:
    driver: bridge
